[package]
name = "DogCollar"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
actix-rt = "2.10.0"
serde = {version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
dotenv = "0.15.0"
config = "0.15.5"
env_logger = "0.11.6"